apiVersion: v1
metadata:
  name: ign
baseDomain: enoks.fr
compute: 
- name: worker
  replicas: 2
  architecture: amd64
controlPlane: 
  name: master
  replicas: 3
  architecture: amd64
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OVNKubernetes 
  serviceNetwork: 
  - 172.30.0.0/16
  machineNetwork: # sinon il va jouter 10.0.0.0/16 par defaut
  - cidr: 192.168.1.0/24
platform:
  none: {}
fips: false 
pullSecret: 'xxxx' 
sshKey: 'ssh-zzz' 
